"""
Django settings for core_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&y4os%7_s^7#*^k3lbd7rervmr^+u4_d5ys4^_f4qybjts5n7g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.localhost', '*']

# Application definition

# Apps that manage tenant onboarding, subscription billing, and multi-domain routing
SHARED_APPS = [
    'django_tenants',  # Must be placed at the very top
    'tenants',         # Our custom tenant onboarding app

    # Core Django apps needed globally
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'users',          # Custom user model with roles and biometric data
]

# Apps whose tables will be isolated within each individual tenant's store schema
TENANT_APPS = [
    'django.contrib.admin',  # Keep tenant admin history beside tenant users
    'django.contrib.auth',  # Cashiers/Managers are isolated inside their specific store
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Our feature modules
    'rest_framework.authtoken',
    'inventory',  # Products separate per store
    'sales',      # Receipts separate per store
    'users',      # Custom user roles per store
]

# Combined application list required by Django's execution engine
INSTALLED_APPS = []
for app in SHARED_APPS + TENANT_APPS:
    if app not in INSTALLED_APPS:
        INSTALLED_APPS.append(app)

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',  # MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',           # Excellent for static assets
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_backend.tenant_urls'
PUBLIC_SCHEMA_URLCONF = 'core_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# core_backend/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend', # Custom engine for multi-tenancy
        'NAME': 'saas_pos_db',
        'USER': 'pos_admin',
        'PASSWORD': 'secure_pos_password123',
        'HOST': '127.0.0.1',                          # Points to our localhost where Docker mapped port 5432
        'PORT': '5432',
    }
}

# Tell Django how to route queries across multiple schemas
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Define which models represent the Tenant and its Domain routing maps
TENANT_MODEL = 'tenants.Client'  # We will build this model next
TENANT_DOMAIN_MODEL = 'tenants.Domain'  # We will build this model next


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Add this line
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Add this line if you have a static folder
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Force Django to use the media URL for tenant domains
FORCE_SCRIPT_NAME = None  # This allows media to work with tenant domains

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}
