# Generated by Django 6.0.6 on 2026-07-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription_plan',
            field=models.CharField(default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='suspended_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
