# Generated by Django 6.0.6 on 2026-07-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_subscription_plan_client_subscription_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('target_tenant', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='trial_period_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='client',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
