# Generated by Django 6.0.6 on 2026-07-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_backfill_trial_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='TRIAL', max_length=20),
        ),
    ]
