# Generated by Django 6.0.6 on 2026-07-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_client_owner_email_alter_client_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(max_length=100)),
                ('tenant_name', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant_schema', '-timestamp'], name='tenants_log_tenant__91ca19_idx'), models.Index(fields=['-timestamp'], name='tenants_log_timesta_de3b4f_idx')],
            },
        ),
    ]
