# Generated by Django 6.0.6 on 2026-07-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_loginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cashier_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='last_known_engagement',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
