# Generated by Django 6.0.6 on 2026-07-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (e.g., 10 for 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Optional product image', null=True, upload_to='product_images/'),
        ),
    ]
