# Generated by Django 6.0.6 on 2026-07-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_product_discount_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_processed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
