from django.contrib.auth.models import AbstractUser
from django.db import models
from core_backend.models_base import AbstractBaseUUIDModel

class User(AbstractUser, AbstractBaseUUIDModel):
    ROLE_CHOICES = [
        ('ADMIN', 'SaaS Administrator'),
        ('MANAGER', 'Store Manager'),
        ('CASHIER', 'Store Cashier'),
    ]
    
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='CASHIER')
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    
    # Biometric data storage for OpenCV Face Recognition
    # Stores the raw facial embedding array generated by OpenCV/dlib (e.g., [0.12, -0.04, ...])
    facial_embedding = models.JSONField(
        blank=True, 
        null=True, 
        help_text="128-dimensional vector array representing the user's face print."
    )
    
    # Track physical device binding for cashiers (Max 10 cashiers per terminal pool)
    assigned_terminal_id = models.CharField(
        max_length=100, 
        blank=True, 
        null=True, 
        help_text="Binds a cashier profile to a physical desktop machine identifier."
    )

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return f"{self.username} - {self.get_role_display()}"

    @property
    def is_manager_or_above(self):
        return self.role in ['ADMIN', 'MANAGER']