# Generated by Django 6.0.6 on 2026-07-10 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-created_at'], name='sales_sale_created_66311a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sales_sale_status_532843_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier'], name='sales_sale_cashier_968a81_idx'),
        ),
    ]
