# Generated by Django 6.0.6 on 2026-07-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Product cost price at the exact moment of purchase — used for profit margin reporting, frozen so later cost changes don't distort historical margins.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price at the exact moment of purchase', max_digits=12),
        ),
    ]
